### ISSUE TITLE
Implementar testes

### ISSUE THREAD

**Issue by Marlysson** [rogerio410/InthegraAPI-STRANS-Python#1]
Adicionar implementação de testes unitários na api.
- Libs usadas:
  - unittest
  - mock
  - requests
- Motivação
  - unittest para fazer os tests unitários.
  - mock para isolar a requisição à api da strans
  - requests para abstrair as chamadas à api.

**Comment by erickpassos** [comment]
Are you guys still working on this?

**Comment by rogerio410** [comment]
No, but Guilherme will show it in a Python Conf this month.

Em qui, 17 de mai de 2018 07:40, erickpassos <notifications@github.com>
escreveu:
